name: GitHub Metrics

on:
  # Schedule updates (every day at 00:00)
  schedule: [{cron: "0 */6 * * *"}]  # Toutes les 6 heures
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: [ "main", "master" ] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ThomasDlv0
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris

          # Plugins
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          plugin_isocalendar: no
          plugin_isocalendar_duration: full-year

          plugin_languages: no
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_habits: no
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          plugin_notable: no
          plugin_notable_from: organization
          plugin_notable_types: commit

          plugin_discussions: no
          plugin_discussions_categories: yes

          plugin_activity: no
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          plugin_code: no
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public

          plugin_followup: no
          plugin_followup_archived: yes
          plugin_followup_sections: repositories

          plugin_reactions: no
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100

          plugin_people: no
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

          plugin_stars: no
          plugin_stars_limit: 4

          plugin_topics: no
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_topics_limit: 15